language: node_js

node_js:
- 6

sudo: false

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      node_js: 5

cache:
  directories:
    - node_modules

notifications:
  email: true
  webhooks:
    on_success: change
    on_failure: always
    on_start: never

before_install:
  - npm i -g npm
  - npm config set spin false
  - npm config set progress false
  - npm install typings -g

before_script:
  - npm install
  - typings install
  - npm run tsc

script:
  - npm test

after_failure:
  - cat /home/travis/build/dajk/MEAN2/npm-debug.log

branches:
  only: master
